# Generated by Django 4.2.3 on 2023-07-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
